filter:
    excluded_paths:
        - src/*
        - languages/*
        - assets/*

checks:
    coding_standard:
        name: WordPress

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
